import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Index from "../components/navbar";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>WETLAND CULTURAL AND EDUCATIONAL FOUNDATION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Index />
      </body>
    </Box>
  );
}
